FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

COPY Backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Backend/ .

EXPOSE 8000

CMD sh -c "sleep 10 && \
           python manage.py migrate && \
           python manage.py runserver 0.0.0.0:8000"
