# Third-party libraries
from PIL import Image
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Local libraries
from fashion_web_app.services.chat_bot import ChatBot
from fashion_web_app.services.similarity_fashion import SimilarityFashion

# Configure logging
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize services
similarity_fashion = SimilarityFashion()
chat_bot = ChatBot()

@csrf_exempt
def similarity_fashion_response(request):
    """
    Based on the provided image, the model will suggest similar products corresponding to the categories found.

    Args:
    - request: HTTP request containing the image provided by the user.

    Return:
    - information_clothes: List a dictionary of similar products including images and product information.

    """
    if request.method == "POST":
        try:
            image = request.FILES["image"]
            pil_image = Image.open(image).convert("RGB")
            information_clothes = similarity_fashion(pil_image)  
            return JsonResponse({"result": information_clothes})
        except Exception as e:
            logger.error(f"Error processing request: {e}")
            return JsonResponse({"error": str(e)}, status=500)

    logger.info("Received non-POST request")
    return JsonResponse({"result": False})

@csrf_exempt
def chatbot_response(request):
    """
    Based on the user's message, the LLM model will generate text and respond to the user in the most natural and accurate way.

    Args:
    - request: HTTP request containing the user's message.

    Return:
    - bot_message: The response message generated by the model.
    
    """
    if request.method == "POST":
        try:
            user_message = request.POST.get('userMessage')
            print("\nUser message:", user_message)

            bot_message = chat_bot(user_message)  
            print("Chatbot response:", bot_message)

            return JsonResponse({"result": bot_message})
        except Exception as e:
            logger.error(f"Error processing request: {e}")
            return JsonResponse({"error": str(e)}, status=500)

    logger.info("Received non-POST request")
    return JsonResponse({"result": False})
